WeBankPartners/open-monitor

- monitor-ui/src/assets/config/api-center.json
- monitor-ui/src/assets/js/httpRequestEntrance.js
- monitor-ui/src/assets/veeValidate/VeeValidate.js
- monitor-ui/src/components/components/modal.vue
- monitor-ui/src/components/pages/monitor-config/Object-management.vue
- monitor-ui/src/components/pages/monitor-config/Threshold-management.vue
> 85 entpoint management

- monitor-ui/src/assets/config/api-center.json
- monitor-ui/src/components/components/table-page/extend-table.vue
- monitor-ui/src/components/components/table-page/page.vue
- monitor-ui/src/components/pages/alarm-management.vue
- monitor-ui/src/components/pages/monitor-config/Group-management.vue
- monitor-ui/src/components/pages/monitor-config/Log-management.vue
- monitor-ui/src/components/pages/monitor-config/Monitor-config-index.vue
- monitor-ui/src/components/pages/monitor-config/Object-management.vue
- monitor-ui/src/main.js
- monitor-ui/src/router.js
- monitor-ui/src/store.js
> 72 log management

- monitor-ui/package-lock.json
- monitor-ui/package.json
- monitor-ui/src/assets/config/api-center.json
- monitor-ui/src/assets/config/chart-rely.js
- monitor-ui/src/assets/css/common.less
- monitor-ui/src/components/components/Charts.vue
- monitor-ui/src/components/components/Max-chart.vue
- monitor-ui/src/components/components/Search-input.vue
- monitor-ui/src/components/components/Search.vue
- monitor-ui/src/components/components/notice.vue
- monitor-ui/src/components/index.vue
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/DIY-view/view-config-index.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/main-view.vue
- monitor-ui/src/components/pages/metric-config.vue
- monitor-ui/src/components/pages/portal.vue
- monitor-ui/src/components/sub-c/menu.vue
- monitor-ui/src/main.js
- monitor-ui/src/router.js
- monitor-ui/src/store.js
> 77 view config layout

- build/docker-compose.tpl
- build/install.sh
- monitor-server/api/v1/agent/register.go
- monitor-server/conf/docker/monitor.json
> Update docker compose doc

- monitor-ui/src/assets/js/httpRequestEntrance.js
- monitor-ui/src/components/components/Charts.vue
- monitor-ui/src/components/components/Search.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/main-view.vue
- monitor-ui/src/components/pages/metric-config.vue
- monitor-ui/src/components/pages/monitor-config/Log-management.vue
- monitor-ui/src/components/pages/monitor-config/Threshold-management.vue
> 92 bug fix

- monitor-ui/src/assets/config/chart-rely.js
- monitor-ui/src/components/components/Single-chart.vue
- monitor-ui/src/components/pages/metric-config.vue
Update charts configuration files
> #120 Update charts configuration files

- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/DIY-view/view-config-index.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/vue.config.js
> 143 charts resize

- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/components/pages/monitor-config/Endpoint-management.vue
#147 Optimization endpoint add
> #147 Optimization endpoint add

- monitor-ui/src/components/index.vue
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/DIY-view/view-config-index.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/portal-o.vue
- monitor-ui/src/components/pages/portal.vue
> 157 screen adaptation

- monitor-ui/src/assets/config/api-center.json
- monitor-ui/src/assets/config/chart-rely.js
- monitor-ui/src/assets/js/validate.js
- monitor-ui/src/components/components/Charts.vue
- monitor-ui/src/components/components/Max-chart.vue
- monitor-ui/src/components/components/Single-chart.vue
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/DIY-view/view-config-index.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/metric-config.vue
- monitor-ui/src/components/pages/monitor-config/Endpoint-management.vue
- monitor-ui/src/components/pages/portal.vue
> 120 optimize chart rendering

- monitor-server/api/v1/agent/export.go
- monitor-server/api/v1/agent/register.go
- monitor-server/api/v1/alarm/alarm.go
- monitor-server/api/v1/alarm/grp.go
- monitor-server/api/v1/alarm/log_monitor.go
- monitor-server/api/v1/alarm/maintain.go
- monitor-server/api/v1/alarm/strategy.go
- monitor-server/api/v1/dashboard/custom.go
- monitor-server/api/v1/dashboard/dashboard.go
- monitor-server/api/v1/user/auth.go
- monitor-server/services/db/alarm.go
- monitor-ui/public/index.html
- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/components/sub-c/menu.vue
> WeCube-Monitor(功能演示版)

- README.md
- README_EN.md
> #Update README

- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/assets/veeValidate/VeeValidate.js
- monitor-ui/src/components/components/Search.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/monitor-config/Group-management.vue
- monitor-ui/src/components/sub-c/menu.vue
- monitor-ui/src/main.js
> 180 bug fix

- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/portal.vue
> Update chart colors

- monitor-ui/src/assets/js/httpRequestEntrance.js
- monitor-ui/src/assets/veeValidate/VeeValidate.js
- monitor-ui/src/components/components/Charts.vue
- monitor-ui/src/components/components/Search.vue
- monitor-ui/src/components/components/Single-chart.vue
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/Search-homepage.vue
- monitor-ui/src/components/pages/main-view.vue
- monitor-ui/src/components/pages/monitor-config/Log-management.vue
- monitor-ui/src/components/pages/monitor-config/Threshold-management.vue
- monitor-ui/src/components/pages/portal.vue
- monitor-ui/src/components/sub-c/menu.vue
- monitor-ui/src/main.js
> 116 bug fix

- monitor-ui/src/components/components/Search.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/metric-config.vue
- monitor-ui/src/components/pages/portal.vue
> #200 bug fix

- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/system-monitoring.vue
- monitor-ui/src/components/sub-c/menu.vue
- monitor-ui/src/router.js
> 224 system monitoring

- monitor-ui/src/components/pages/monitor-config/Log-management.vue
- monitor-ui/src/components/pages/monitor-config/Threshold-management.vue
> #239 bug fix

- monitor-ui/src/components/pages/system-monitoring/system-monitoring.vue
> Update system monitoring

- monitor-ui/src/assets/config/chart-rely.js
- monitor-ui/src/components/components/Max-chart.vue
- monitor-ui/src/components/components/Single-chart.vue
- monitor-ui/src/components/pages/DIY-view/edit-view.vue
- monitor-ui/src/components/pages/DIY-view/view-chart.vue
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/src/components/pages/metric-config.vue
- monitor-ui/src/components/pages/portal.vue
- monitor-ui/src/components/pages/system-monitoring/sys-view-chart.vue
- monitor-ui/src/components/pages/system-monitoring/system-monitoring.vue
> Upgrade chart configuration

- monitor-ui/src/assets/js/httpRequestEntrance.js
- monitor-ui/src/components/pages/DIY-view/view-config.vue
- monitor-ui/vue.config.js
> #258 Bug fix

- build/plugin/register.xml
> #Update register.xml

- monitor-server/api/api.go
- monitor-server/api/v1/agent/export.go
> Update host register

- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/components/menu.vue
- monitor-ui/src/views/monitor-config/endpoint-management.vue
#249 Process monitoring configuration
> #249 Process monitoring configuration

- .gitignore
- build/plugin/register.xml
- monitor-server/api/api.go
- monitor-server/api/v1/agent/install.go
- monitor-server/api/v1/alarm/process.go
- monitor-server/models/alarm.go
- monitor-server/models/process.go
- monitor-server/services/db/alarm.go
- monitor-server/services/db/process.go
Update register xml && Add process curd
> Update register xml && Add process curd

- monitor-ui/src/assets/js/gridUtils.js
- monitor-ui/src/views/custom-view/view-config.vue
- monitor-ui/src/views/dashboard.vue
- monitor-ui/src/views/system-monitoring/system-monitoring.vue
> #300 Upgrade custom view

- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/components/search.vue
- monitor-ui/src/views/monitor-config/endpoint-management.vue
#289 Business collection configuration
> 289 business collection configuration

- monitor-ui/src/views/monitor-config/group-management.vue
> #310 fix threshold export bug

- monitor-ui/src/assets/js/httpRequestEntrance.js
- monitor-ui/src/components/menu.vue
- monitor-ui/src/views/login.vue
- monitor-ui/src/views/user-management/role-management.vue
> 375 upgrade account

- monitor-ui/src/components/search.vue
- monitor-ui/src/components/single-chart.vue
- monitor-ui/src/store.js
- monitor-ui/src/views/endpoint-view.vue
- monitor-ui/src/views/recursive-view/recursive.vue
> #385 recursive view

- monitor-ui/src/components/search-input.vue
- monitor-ui/src/components/search.vue
- monitor-ui/src/components/table-page/table.vue
- monitor-ui/src/views/custom-view/edit-view.vue
- monitor-ui/src/views/metric-config.vue
- monitor-ui/src/views/monitor-config/endpoint-management.vue
- monitor-ui/src/views/monitor-config/log-management.vue
- monitor-ui/src/views/monitor-config/threshold-management.vue
- monitor-ui/src/views/user-management/user-management.vue
> #373 Add table tags

- monitor-ui/src/components/search.vue
> 385 fix search component

- monitor-ui/src/store.js
- monitor-ui/src/views/endpoint-view.vue
- monitor-ui/src/views/index.vue
- monitor-ui/src/views/recursive-view/recursive.vue
#402 enhance recursive view switch
> #402 Enhance recursive view switch

- monitor-ui/src/assets/js/axiosHttp.js
- monitor-ui/src/views/monitor-config/group-management.vue
#387 Add token for export & import
> #387 Add token to export & import

- monitor-ui/src/assets/config/api-center.json
- monitor-ui/src/views/monitor-config/group-management.vue
#387 Update group-manegement export url config
> #387 Update group-manegement export url config

- monitor-ui/src/store.js
- monitor-ui/src/views/endpoint-view.vue
- monitor-ui/src/views/recursive-view/recursive.vue
> #425 Enhance recursive view

- monitor-ui/src/views/endpoint-view.vue
- monitor-ui/src/views/recursive-view/recursive.vue
> Upgrade recursive view

- monitor-ui/src/views/alarm-management.vue
> Add tags to delete alarms

- monitor-ui/src/assets/config/api-center.json
- monitor-ui/src/assets/locale/lang/en.json
- monitor-ui/src/assets/locale/lang/zh-CN.json
- monitor-ui/src/views/monitor-config/group-management.vue
> #411 Add authority management

- monitor-ui/package-lock.json
- monitor-ui/src/components/search-input.vue
- monitor-ui/src/components/search.vue
- monitor-ui/src/views/endpoint-view.vue
#463 adaptation endpoint query interface
> 463 adaptation endpoint query interface

- monitor-ui/src/router-plugin-p.js
- monitor-ui/src/router-plugin.js
#482 fixed view chart in wecube 404
> #482 fixed view chart in wecube 404

- monitor-ui/src/components/charts.vue
- monitor-ui/src/components/max-chart.vue
- monitor-ui/src/views/endpoint-view.vue
- monitor-ui/src/views/portal.vue
- monitor-ui/src/views/recursive-view/recursive.vue
> 506 recursive view zoom

- monitor-ui/src/assets/config/chart-rely.js
- monitor-ui/src/components/custom-chart.vue
- monitor-ui/src/views/custom-view/edit-line-view.vue
- monitor-ui/src/views/custom-view/edit-pie-view.vue
- monitor-ui/src/views/custom-view/view-chart.vue
- monitor-ui/src/views/custom-view/view-config.vue
- monitor-ui/src/views/dashboard.vue
- monitor-ui/src/views/system-monitoring/sys-view-chart.vue
#566 Store custom view settings
> 566 chart type

- monitor-server/api/v1/alarm/alarm.go
> for循环中存在隐式内存别名
